alias: Publish tank1_depth1 temperature on change
description: ""
triggers:
  - entity_id: sensor.tank1_depth1_temperature
    trigger: state
conditions: []
actions:
  - data:
      topic: home/test
      payload: |
        tank1_depth1: {{ states('sensor.tank1_depth1_temperature') }}°C
      qos: 0
    action: mqtt.publish
mode: single
